services:
  slskd:
    image: ghcr.io/slskd/slskd:latest
    container_name: slskd
    environment:
      - SLSKD_REMOTE_CONFIGURATION=true
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./slskd/config:/config
      - ./slskd/data:/app/slskd
      - /mnt/Files/Music:/music 
    ports:
      - 5030:5030
      - 5031:5031
    restart: unless-stopped
