services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    
    environment:
      - PUID=1000 # Run 'id -u' to check your ID
      - PGID=100  # Run 'id -g' to check your Group ID
      - TZ=Asia/Dhaka
      - WEBUI_PORT=8080
    volumes:
      - ./config:/config
      - /mnt/Files/Torrent:/downloads #Change this to the actual hard drive path
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
